### PR TITLE
Fix #243 - Fixed jquery-ui slider js file path

### LINKED ISSUE #243: $(...).find(...).slider is not a function is not a function error with Magento 2.4.4
After upgrading Magento to version 2.4.4 the price-slider is not working anymore. After I open the console, I can see the following error: `$(...).find(...).slider is not a function is not a function`

### Preconditions
Magento Version : 2.4.4

### Steps to reproduce
Go to any product with layered navigation
The price slider is now broken and there is an error displayed in your console.

### Expected result
The price slider is working.

### Actual result
The price slider is broken and throws an error.
image

### PR DESCRIPTION
**Pull request by glevhen**

### CODE REVIEW

**Comment by ah-net** [comment]
Also seems to fix issue https://github.com/EmicoEcommerce/Magento2Tweakwise/issues/239

**Comment by ahuininga-orisha** [comment]
Tested and works on magento 2.4.4. Still needs to be tested in earlier versions to make sure its backwards compatible.
